#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for optimizer/tf
#
# IDENTIFICATION
#    src/backend/optimizer/tf/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/optimizer/tf
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = tf.o

include $(top_srcdir)/src/backend/common.mk